### ISSUE TITLE
T3 7.6: Fehlerhafte SQL-Query und fehlende Ausgabe im FE

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league_fe#13]
Auf einer FE-Seite, in der ich einen Spielplan ausgebe, bekomme ich diese Fehlermeldung für jedes Team im Spielplan angezeigt:
```
array(4 items)
   caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
   ERROR => 'You have an error in your SQL syntax; check the manual that corresponds to y
      our MySQL server version for the right syntax to use near 'FROM tx_cfcleague
      _teams WHERE uid='****' AND NOT deleted LIMIT 1' at line 1' (211 chars)
   lastBuiltQuery => 'SELECT FROM tx_cfcleague_teams WHERE uid='****' AND NOT deleted LIMIT 1' (73 chars)
   debug_backtrace => 'call_user_func#34 // {closure}# 
// TYPO3\CMS\Frontend\Http\Application->run#33 
// TYPO3\CMS\Core\Core\Bootstrap->handleRequest#78 
// TYPO3\CMS\Frontend\Http\RequestHandler->handleRequest#302 
// TYPO3\CMS\Frontend\Page\PageGenerator::renderContent#216 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGet#210 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#805 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render#859 
// TYPO3\CMS\Frontend\ContentObject\FluidTemplateContentObject->render#943 
// TYPO3\CMS\Frontend\ContentObject\FluidTemplateContentObject->renderFluidView#102 
// TYPO3\CMS\Fluid\View\AbstractTemplateView->render#300 
// FluidCache_Standalone_layout_Default_07c91cf3b65d4b767f87d52fcd3f165043c0f0ba->render#189 
// TYPO3\CMS\Fluid\ViewHelpers\RenderViewHelper::renderStatic#175 
// TYPO3\CMS\Fluid\View\AbstractTemplateView->renderSection#121 
// FluidCache_Standalone_template_file_DefaultSubNavLeft_d9838e0d5fb52d986c166215d6090b68cf98b1fb->section_62bce9422ff2d
      14f69ab80a154510232fc8a9afd#230
// TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender#101 
// TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod#249 
// call_user_func_array#268 
// TYPO3\CMS\Fluid\ViewHelpers\CObjectViewHelper->render# 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#119 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render#859 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectArrayContentObject->render#943
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGet#41 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#805 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render#859 
// TYPO3\CMS\Frontend\ContentObject\ContentContentObject->render#943 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#97 
// TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#841 
// TYPO3\CMS\Frontend\Co...' (5123 chars)
```

Außerdem:
Ich habe von Typo3 6.2 auf Typo3 7.6 geupdated. Die Ausgabe von allen Inhalten des Plugins werden

- nur angezeigt, wenn ich eine aktive Backend-Session habe
- im Backend den Seiteninhalt speicher, im Install-Tool alle Caches lösche und dann das Frontend aktuallisiere. Wenn ich dann im Backend etwas anderes mache (z.B. eine Extension installieren) ist die Anzeige im Frontend wieder weg und ich muss die Schritte wiederholen. Die Schritte sind dabei für jeden Seiteninhalt einzeln durchzuführen. Ich kann nicht alle Seiteninhalte öffnen, speichern und dann zum Schluss den Cache löschen, sondern muss das für jeden Seiteninhalt einzeln machen.

Ich habe die aktuellen Versionen von `rn_base`, `cfc_league` und `cfc_league_fe`. Andere Plugins `news` oder `cal` zeigen den Inhalten im FE ohne Probleme an.

**Comment by digedag** [comment]
Ich hab auch die Ausgabe mal von #6 rausgeschoben.
Bitte aktualisiert nochmal cfc_league und cfc_league_fe. Beide Versionen funktionieren jetzt. Ich habe in beiden Extensions eine composer.json integriert. TYPO3 nutzt in 7.6 den Composer für das Autoloading der PHP-Klassen. Vielleicht löst das ja dein Problem.

Die SQL-Query kann ich leider nicht nachvollziehen. Ich hab den Stacktrace mal etwas aufgeräumt. Darin ist überhaupt keine Klasse von T3sports zu sehen. Irgendwo müsste ja mal das Plugin auftauchen. Warum TYPO3 direkt eine (fehlerhafte) SQL-Query ausführt, weiß ich leider nicht.

**Comment by stemeda** [comment]
Danke für die Rückmeldung. Ich habe gestern Typo3 auf 7.6.15 aktualisiert. Dannach funktionierte es. Ich hatte aber keine Zeit für weitere Tests. Ich habe heute cfc_league und cfc_league_fe aktualisiert und weiter gestestet. Es scheint alles zu funktionieren!? Ob mein Typo3 Core korrupt war?
