### ISSUE TITLE
LeagueTableAllTime

### ISSUE THREAD

**Issue by al-daten** [digedag/cfc_league_fe#17]
Version vom 17.1.
`exception 'TYPO3\CMS\Core\Error\Exception' with message 'PHP Catchable Fatal Error: Argument 2 passed to TYPO3\CMS\Core\Utility\GeneralUtility::array_merge() must be of the type array, null given in /var/www/typo3_src/typo3_src-7.6.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1771' in /var/www/typo3_src/typo3_src-7.6.15/typo3/sysext/core/Classes/Error/ErrorHandler.php:111
Stack trace:
#0 /var/www/typo3_src/typo3_src-7.6.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php(1771): TYPO3\CMS\Core\Error\ErrorHandler->handleError(4096, 'Argument 2 pass...', '/var/www/typo3_...', 1771, Array)
#1 [internal function]: TYPO3\CMS\Core\Utility\GeneralUtility::array_merge(Array, NULL)
#2 /var/www/vhosts/jufuba.at/jufuba2017/typo3conf/ext/rn_base/Classes/Utility/T3General.php(55): call_user_func_array(Array, Array)
#3 /var/www/vhosts/jufuba.at/jufuba2017/typo3conf/ext/cfc_league_fe/views/class.tx_cfcleaguefe_views_LeagueTableAllTime.php(84): Tx_Rnbase_Utility_T3General::__callStatic('array_merge', Array)
#4 /var/www/vhosts/jufuba.at/jufuba2017/typo3conf/ext/cfc_league_fe/views/class.tx_cfcleaguefe_views_LeagueTableAllTime.php(84): Tx_Rnbase_Utility_T3General::array_merge(Array, NULL)
#5 /var/www/vhosts/jufuba.at/jufuba2017/typo3conf/ext/cfc_league_fe/views/class.tx_cfcleaguefe_views_LeagueTableAllTime.php(43): tx_cfcleaguefe_views_LeagueTableAllTime->_createTable('\r\n
 `

**Comment by al-daten** [comment]
Fatal error: Access level to tx_cfcleaguefe_views_LeagueTableAllTime::_cropTable() must be public (as in class tx_cfcleaguefe_views_LeagueTable) in /var/www/vhosts/jufuba.at/jufuba2017/typo3conf/ext/cfc_league_fe/views/class.tx_cfcleaguefe_views_LeagueTableAllTime.php on line 32

**Comment by digedag** [comment]
Ich hoffe, nun funktioniert es. Kann es leider im Moment nicht selber testen.

**Comment by al-daten** [comment]
Ja, jetzt funktioniert's.
Und vielen Dank für die Arbeit, ich weiß die AllTime-Tabelle machst Du 
nur für mich.
lg
thomas

Am 06.03.2017 um 21:07 schrieb René Nitzsche:
