### ISSUE TITLE
"Sorry, no team found..." nach Update auf aktuellste Version

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league_fe#2]
Nach dem Update auf die aktuellste Version 1.0.0 erhalte ich bei meinen Mannschaftsprofilen die Ausgabe "Sorry, no team found...".
Auf der selben Seite werden auch Tabellenausschnitte und Spiele angezeigt, diese werden ausgegeben.
Ich habe mit Screnshots mal meine Konfiguration festgehalten.

![150406-cfcleague-fe-noteamfound](https://cloud.githubusercontent.com/assets/863722/7003452/e8e13d1c-dc5a-11e4-80aa-d5a083efa129.png)

![150406-cfcleague-fe-noteamfound-02](https://cloud.githubusercontent.com/assets/863722/7003480/54ada3e6-dc5b-11e4-9d4c-86a462c52920.png)

![150406-cfcleague-fe-noteamfound-03](https://cloud.githubusercontent.com/assets/863722/7003479/54abf3a2-dc5b-11e4-946a-544a3ea654c3.png)

![150406-cfcleague-fe-noteamfound-04](https://cloud.githubusercontent.com/assets/863722/7003478/54aa43e0-dc5b-11e4-9912-db6b6fb82cee.png)

Ich habe eine Vorlage erstellt, die ich auf allen Seiten verlinke, auf denen ich das Plugin benötige. Die Einstellung der Altersgruppe mache ich dann via TS. Bei Spielen klappt das ja nach wie vor wunderbar.

**Comment by bastians** [comment]
Sag mal, hatten wir das nicht schon mal diskutiert? Damals noch bei Sourceforge?

**Comment by digedag** [comment]
Also im Ablauf des Views solltest du an [dieser Stelle](https://github.com/digedag/cfc_league_fe/blob/master/actions/class.tx_cfcleaguefe_actions_TeamView.php#L69) vorbeikommen. Die Datenbankabfrage startet dann im [Club-Model](https://github.com/digedag/cfc_league_fe/blob/master/models/class.tx_cfcleaguefe_models_club.php#L75).
Aktiviere da mal den Debug indem du den letzten Parameter von 0 auf 1 änderst:

<code php>
  return tx_rnbase_util_DB::doSelect($what,$from,$options,1);
</code>

**Comment by bastians** [comment]
Hat es mit dem MAX_JOIN_SIZE zu tun?

![2015-04-10 10_37_47-kader _ fv lochgau e v](https://cloud.githubusercontent.com/assets/863722/7084442/bc229b48-df6d-11e4-9d03-31efcfdff461.png)

**Comment by bastians** [comment]
Aaah. Schau mal, das hatten wir doch schon mal: http://www.typo3.net/forum/thematik/zeige/thema/115831/

Habe in der Datei cfc_league_fe/models/class.tx_cfcleaguefe_models_club.php in Zeile 70 wieder folgendes eingefügt:

> mysql_query('SET SQL_BIG_SELECTS=1');"

Nun klappt es. Nur bekommen wir das irgendwie update-kompatibel?

**Comment by digedag** [comment]
Du solltest dir die Extension [devlog](http://typo3.org/extensions/repository/view/devlog) installieren. Außerdem kannst du in den Extension-Einstellungen von rn_base eine Mailadresse konfigurieren, an die du schwerwiegende Fehler geschickt bekommst. :-)

Die Option mit dem SQL_BIG_SELECTS solltest du auch im INSTALL-Tool bei den Datenbank-Optionen machen können. Da sollten sich Angaben zur Verwendung von utf8 stehen. Dann ist das aus der Extension raus.

Das Setzen von passenden Indexen ist übrigens nicht ganz so einfach, weil hier nicht ganz klar ist, welche Spalte eigentlich das Problem verursacht. Und es ist ja nicht so, daß wirklich ein riesiger Select entsteht. Am Ende wird ja meist nur ein Datensatz gefunden... Vermutlich liegt es an dem FIND_IN_SET. Dafür kann man aber gar keinen Index setzen. Das müsste sauber über eine Zwischentabelle gelöst werden. Der Aufwand einer Umstellung ist aber recht groß.

**Comment by bastians** [comment]
Ok, danke. Dann versuche ich das mal in den Einstellungen zu konfigurieren.

**Comment by bastians** [comment]
Ganz kurz: Habe schon eine Emailadresse in den rn_base-Einstellungen hinterlegt, da kam nichts.

**Comment by digedag** [comment]
Na du bekommst natürlich nur eine Mail, wenn ein Fehler auftritt. Der wird dann auch jeweils bei devlog mit angezeigt. :)

**Comment by bastians** [comment]
Das ist klar. Hätte dann aber nicht für den Fehler, der auftreten ist, eine Meldung kommen sollen?

**Comment by digedag** [comment]
Oh ja, wenn die Adresse schon drin stand, dann hättest du eigentlich etwas bekommen müssen...

**Comment by bastians** [comment]
Ich beobachte das mal, sollte ein neuer Fehler auftauchen.

**Comment by digedag** [comment]
Der letzte Commit gehörte zu einem anderen Ticket. Einfach ignorieren! ;)
