### ISSUE TITLE
Feste Position bei Tabellenberechnung

### ISSUE THREAD

**Issue by digedag** [digedag/cfc_league_fe#27]
Es sollte über die Wettbewerbsstrafe möglich sein, einem Team eine feste Position in der Tabelle zu zuordnen. Damit lassen sich komplexe Fehler in der automatischen Berechnung schnell manuell korrigieren. 
Aktuell ist es nur möglich ein Team fest an Ende der Tabelle zu setzen.

**Comment by digedag** [comment]
Das Feature ist jetzt umgesetzt. **WICHTIG** Das Feld *Zwangsabstieg* wurde durch *Feste Position* ersetzt. Damit ändert sich das Verhalten. Bisher war Zwangsabstieg eine Checkbox, neu kann man nun die gewünschte Position direkt eintragen. Bei einer Checkbox wird in die Datenbank eine **1** eingetragen. Nach dem Update, werden die vorhandenen Zwangsabstiege also automatisch auf Position 1 gesetzt. **Das muss manuell geändert werden.**
Bei einem gewünschten Zwangsabstieg kann man einfach den Wert **-1** eintragen.

**Comment by entaxi57** [comment]
Hallo René,

klappt einwandfrei.

DANKE!!!!

**Comment by entaxi57** [comment]
Hallo René,

ich habe mir gerade die Tabellen nochmals angeschaut. Leider scheint sich jetzt doch ein Fehler eingeschlichen zu haben.  Wenn man z.B. in der Tabelle, bei dem der 1. und 2. Platz und außerdem der 4. und 5. Platz getauscht werden muss, dann wird die Mannschaft, die auf den 2. Platz geändert wurde, auch auf den 5. Platz angezeigt. Die Mannschaft, die den 5. Platz eigentlich inne hat, wird nicht mehr angezeigt - siehe https://www.crowntown.de/index.php?id=81.

Hoffe, dass ich mich halbwegs verständlich ausgedrückt habe.

Ich habe die letzte Version aktiv, bevor du Handball mit eingebunden hast.

Ich nutze
php 7.1
T3sports 1.1.1 (07.06.2017 ???)
T3sports FE 1.1.1 (07.06.2017 ???)
rn_base 1.4.1

**Comment by entaxi57** [comment]
Hallo René,

hier noch einigen Anmerkungen:

eingetragene Wettbewerbsstrafen:
TeamID 2 (TSV Burgdorf 1) auf Platz 2
TeamID 5 (Bramstedter TS 1) auf Platz 5

TeamID 2 (TSV Burgdorf 1) wird dann in der Tabelle auf Platz 2 und Platz 5 angezeigt. 
TeamID 5 (Bramstedter TS 1) wird nicht mehr angezeigt.

Wenn ich eine der beiden Korrekturen herausnehme, werden alle Mannschaften wieder angezeigt.

Das Problem tritt auch auf, wenn ich einen anderen Platz zuweise:
TeamID 2 (TSV Burgdorf 1) auf Platz 3
TeamID 5 (Bramstedter TS 1) auf Platz 5

TeamID 2 (TSV Burgdorf 1) wird dann in der Tabelle auf Platz 3 angezeigt.
TeamID 5 (Bramstedter TS 1) wird nicht mehr angezeigt.

In meiner Testumgebung haben die gleichen Mannschaften eine höhere TeamIDs, dort wird die Tabelle korrekt angezeigt.

Kann es damit zusammenhängen, dass das System mit der TeamID und Platznummer durcheinander kommt, wenn zufälligerweise die TeamID und Platznummer identisch sind und dann noch ein 2. Mannschaft korrigiert werden muss? Zu mindestens ist es bei mir so. Ich habe es mit allen Mannschaften in dieser Gruppe probiert und bekomme dann immer das gleiche Problem. Die Mannschaft wird immer 2 x angezeigt bzw. die Mannschaft mit der TeamID 5 wird nicht mehr angezeigt.

mfg
Bernd

**Comment by digedag** [comment]
Ich hab eben noch eine Änderung gemacht. Die könnte auch das beschriebene Problem lösen. Wobei ich das nicht im konkreten Fall angeschaut habe. Aber vielleicht haben wir ja Glück! :wink:

**Comment by entaxi57** [comment]
Hallo René,

werde es schnellstens testen.

**Comment by entaxi57** [comment]
Hallo René,

sieht sehr gut aus. Die Tabelle wird einwandfrei angezeigt.

Danke.

**Comment by digedag** [comment]
Super. Vielen Dank für den Test. Ich mach das Ticket dann wieder zu.

**Comment by entaxi57** [comment]
Hallo René,

gern geschehen.
