### ISSUE TITLE
Core: Error handler (FE): PHP Warning: Declaration of tx_cfcleaguefe_views_LeagueTableAllTime

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league_fe#28]
Hallo René,

habe gerade noch einen php-Fehler gefunden:
"Core: Error handler (FE): PHP Warning: Declaration of tx_cfcleaguefe_views_LeagueTableAllTime::_fillControlTemplate($template, &$itemsArr, $link, $markerName, $configurations) should be compatible with tx_cfcleaguefe_views_LeagueTable::_fillControlTemplate($template, &$itemsArr, &$link, $markerName, &$configurations) in ../typo3conf/ext/cfc_league_fe/views/class.tx_cfcleaguefe_views_LeagueTableAllTime.php line 32"

kann aber nicht feststellen, dass die Anwendung ein Problem hat.

Ich nutze 
php 7.1
T3sports 1.1.1 (05.06.2017)
T3sports FE 1.1.1 (05.06.2017)
rn_base 1.4.1

p.s.
Ist es eigentlich möglich, dass die "LeagueTableAllTime" standardmäßig als 2-Punkte-Tabelle angezeigt wird? Bei mir wird sie immer zuerst als 3-Punkte-Tabelle angezeigt.

Bernd

**Comment by digedag** [comment]
Das Punktsystem sollte man im Plugin auch fest einstellen können. Die Auswahlmöglichkeit ist nur optional.

**Comment by entaxi57** [comment]
Hallo René,

habe gerade die korrigierte Version getestet. Fehler taucht nicht mehr auf.

Super. Danke.

p.s. Leider bekomme ich das Punktsystem nicht hin. Ich weiß nur, dass ich bei den Wettbewerben das Punktesystem einstellen kann. Aber für "LeagueTableAllTime" brauche ich doch keinen neuen Wettbewerb. Oder sehe ich das falsch?
