### ISSUE TITLE
tx_cfcleaguefe_util_ScopeController.php

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league_fe#31]
Hallo René,

habe gerade noch einen php-Fehler gefunden:

`Core: Error handler (FE): PHP Runtime Deprecation Notice: Non-static method tx_cfcleaguefe_util_ScopeController::handleCurrentRound() should not be called statically in /mnt/web110/e2/66/5513066/htdocs/typo3_grau_01/typo3conf/ext/cfc_league_fe/util/class.tx_cfcleaguefe_util_ScopeController.php line (63 bis 67)`

kann aber nicht feststellen, dass die Anwendung ein Problem hat.

Ich nutze
php 7.1
Typo3 7.6.18
T3sports 1.1.1 (ca. 05.07.2017)
T3sports FE 1.1.1 (ca. 05.07.2017)
rn_base 1.4.1

Bernd

**Comment by entaxi57** [comment]
Hallo René,

habe gerade mit der neuen Version getestet. Der Fehler tritt nicht mehr auf. 

Danke.

Bernd

**Comment by digedag** [comment]
Super, danke dir!
