### ISSUE TITLE
Support TYPO3 8.7 LTS

### ISSUE THREAD

**Issue by digedag** [digedag/cfc_league_fe#32]
T3sports sollte unter TYPO3 8.7 ausführbar sein.

**Comment by digedag** [comment]
Installation ist möglich und der Spielplan/Tabelle funktioniert auch. Wenn es irgendwo Probleme gibt, dann bitte einfach hier ins Ticket rein.

**Comment by stemeda** [comment]
Das kann wohl geschlossen werden, oder? Bei mir läuft es seit :-)
