### ISSUE TITLE
Reiter Kontakt (Contact) bei Mannschaften

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league_fe#34]
Hallo René,

ist es vielleicht auch möglich, dass bei den Mannschaften ein Reiter Kontakt (Contact) eingebunden wird?

Wir sind gerade dabei, den einzelnen Mannschaften eine eigene E-Mail-Adresse zu geben. Außerdem haben einigen Mannschaften z.B. bei Facebook eine zusätzliche Seite. Ein eigenes Team Logo ist ja bereits möglich.

**Comment by digedag** [comment]
Also grundsätzlich ist es über [die normalen Mechanismen in TYPO3](http://www.sklein-medien.de/tutorials/detail/typo3-datenbanktabellen-um-neue-felder-erweitern/) möglich, weitere Felder hinzuzufügen. Also in einer eigenen Extension die Spalte anlegen und per Override in der TCA bekannt geben.

Für alle Felder in der Datenbank werden automatisch auch Marker erzeugt, die voll per Typoscript konfigurierbar sind. Es macht dann keinen Unterschied, ob das Feld von T3sports kommt, oder nachträglich hinzugefügt wurde. :smile:

**Comment by entaxi57** [comment]
Hallo René,

danke für diesen Link. Werde es mal versuchen.
