### ISSUE TITLE
Error in Statistiken Torschützenliste

### ISSUE THREAD

**Issue by okrgb** [digedag/cfc_league_fe#38]
Hi Sporties!

By calling the Torschützenliste Frontend says: Leider ist ein unerwarteter Fehler aufgetreten.

Versions: cfc_league 1.1.1, cfc_league_fe 1.1.1, rn_base 1.4.5, t3sportstats 0.4.1, TYPO3 CMS 6.2.31

Developer Log says:
cfc_league_fe
Fatal error for action tx_cfcleaguefe_actions_Statistics
class.tx_rnbase_util_Logger.php, line 166

Exception	
message	PHP Runtime Deprecation Notice: Non-static method tx_cfcleaguefe_util_MatchTicker::getMatches4Scope() should not be called statically, assuming $this from incompatible context in .../typo3conf/ext/cfc_league_fe/actions/class.tx_cfcleaguefe_actions_Statistics.php line 80

code 1
file .../typo3_src-6.2.31/typo3/sysext/core/Classes/Error/ErrorHandler.php
line 101
trace ...shows # entries from 0 till 28
_GET id 29048
_POST EMPTY!

Can someone please give me a hint how to handle / to fix this?

**Comment by digedag** [comment]
You should use t3sportstats for statistical features. The stats view in cfc_league_fe is not supported anymore and will be dropped.
And you should always use latest code from Github. The TER versions are only rarely updated. Don't forget to update rn_base!

**Comment by okrgb** [comment]
You are totally right! 
My problem accured after updating from the versions:
cfc_league 1.0.2, cfc_league_fe 1.0.0, rn_base 0.15.0, t3sportstats 	0.3.0 to the current versions.
Thanks for making my day!
