### ISSUE TITLE
Error 500 bei Verwendung des Templates matchtable.php

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league_fe#40]
Wenn ich das Template matchtable.php verwende, bekomme ich leider einen Error 500. Den ViewType habe ich entsprechend gesetzt via

`plugin.tx_cfcleaguefe_competition.matchtable.viewType = PHP`

Das PHP-Errorlog zeigt folgendes:

`PHP Fatal error:  Class 'tx_div' not found in /[...]/fileadmin/templates/layouts/fvl/html/t3sports/matchtable.php on line 4`

Die entsprechenden Extension sind aber installiert.

Muss ich noch etwas beachten?

**Comment by digedag** [comment]
Der PHP-Support für Views wurde entfernt. Wenn ich mal Zeit hab, werde ich mal t3twig integrieren. Aber das kann noch dauern...

**Comment by bastians** [comment]
Oh, ok. Danke für den Hinweis. Dann vielleicht auch die Templates entfernen ;)
