### ISSUE TITLE
Extend tickerLists

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league_fe#44]
Ich möchte die TicketLists erweitern, dass einzelne Bereiche für z.B. die Tore angezeigt werden (danke für den Hinweis in #42:
```ts
plugin {
  tx_cfcleaguefe_report {
    matchreport {
      match {
        tickerLists {
          goals =< lib.t3sports.matchNote
          goals {
            filter.fields.MATCHNOTE.MINUTE.OP_GTEQ_INT = 0
            filter.fields.MATCHNOTE.TYPE.OP_IN_INT = 10,11,12,30,13
            filter.options {
              orderby.MATCHNOTE.MINUTE = DESC
              orderby.MATCHNOTE.EXTRA_TIME = DESC
              orderby.MATCHNOTE.UID = DESC
            }
          }
        }
      }
    }
  }
}
```
Und im Template
```html
###MATCHREPORT###
###MATCH_TICKERS###
<h2>Ticker</h2>
<div id="cfcleague-report-ticker">
        ###MATCH_GOALS###
        <div class="col-sm-6">
                ###MATCH_TICKER_MINUTE### ###MATCH_TICKER_DCSCORE###: ###MATCH_TICKER_DCMESSAGE###
        </div>
        ###MATCH_GOALS###
</div>
###MATCH_TICKERS###
###MATCHREPORT###
```
Aber das Template wird nicht gerendert. Lassen sich die tickerLists nicht erweitern oder fehlt noch etwas?

**Comment by digedag** [comment]
Also zum einen wahr da ein fetter Bug drin. Beim Rendern ist das Script in eine Endlosschleife gelaufen. Das funktioniert jetzt wieder.
Zum anderen ist aber auch deine HTML noch nicht richtig. Nur konntest du das auf Grund des Bugs ja auch nicht richtig testen. :wink: 
Ich hab das Beispiel aber jetzt auch gleich mal mit aufgenommen und zusätzlich die Unterstützung für eigene Subparts mit integriert. Mit deinem Typoscript hast du ja schon die Tore korrekt aus der Datenbank geholt. Zum Rendern hab ich jetzt folgenden Block ins Template gesetzt:

```
###MATCH_GOALS###
<h3>Die Tore</h3>
###MATCH_GOAL###
<div class="col-sm-6">
###MATCH_GOAL_ISGOAL_YES###
        ###MATCH_GOAL_MINUTE### ###MATCH_GOAL_DCSCORE###: TOR durch ###MATCH_GOAL_PLAYER_DCNAME### 
###MATCH_GOAL_ISGOAL_YES###
###MATCH_GOAL_ISGOALOWN_YES###
        ###MATCH_GOAL_MINUTE### ###MATCH_GOAL_DCSCORE###: Eigentor durch ###MATCH_GOAL_PLAYER_DCNAME### 
###MATCH_GOAL_ISGOALOWN_YES###
</div>
###MATCH_GOAL###
###MATCH_GOALS###
```

Die Verwendung des Ticker-Markers **_DCMESSAGE###** funktioniert nicht mehr so gut, weil dieser den Marker für den Spielernamen (###MATCH_TICKER_PLAYER_DCNAME###) verwendet. Dieser müsste nun in der neuen Liste aber ###MATCH_GOAL_PLAYER_DCNAME### heißen. Als Alternative bieten sich [die freien Subparts](https://github.com/digedag/rn_base/blob/master/Documentation/rendering_data.md#eigene-subparts-integrieren) an. Damit wandern auch die Typ-Unterscheidungen ins HTML. Man kann sie als If-Bedingungen nutzen. Im Beispiel sind zwei Subparts, einer für normale Tore und einer für Eigentore. Im Typoscript wird dazu folgendes konfiguriert:
```
lib.t3sports.matchNote {
  subparts {
    isgoal {
      # -> Marker: _ISGOAL_YES###
      marker.visible = YES
      visible = TEXT
      visible.value = 1
      visible.if {
        isInList.field = type
        value = 10,11,12,13
      }
    }
    isgoalown =< lib.t3sports.matchNote.subparts.isgoal
    isgoalown {
      # -> Marker: _ISGOAL_YES###
      visible.if {
        equals.field = type
        value = 30
      }
    }
  }
}
```
Damit sollte man nun alles zusammenbasteln können. Die Subparts lassen sich auch verschachteln, so daß man z.B. einen Subpart für die Unterscheidung von Heim- und Gast-Team erstellen kann und dann innerhalb weitere Subparts für den Typ des Events einbaut.

**Comment by stemeda** [comment]
Vielen Dank! Die Schleife hab ich gestern Abend (ziemlich spät) auch entdeckt :-)

Also könnte ich z.B. alle Karten finden mit:

```
lib.t3sports.matchNote {
  subparts {
    isgoal {
      # -> Marker: _ISGOAL_YES###
      marker.visible = YES
      visible = TEXT
      visible.value = 1
      visible.if {
        isInList.field = type
        value = 10,11,12,13
      }
    }
    isgoalown =< lib.t3sports.matchNote.subparts.isgoal
    isgoalown {
      # -> Marker: _ISGOAL_YES###
      visible.if {
        equals.field = type
        value = 30
      }
    }
    iscard =< lib.t3sports.matchNote.subparts.isgoal
    iscard {
      # -> Marker: _ISCARD_YES###
      visible.if {
        isInList.field = type
        value = 70,71,72
      }
    }
  }
}
```
```
plugin {
  tx_cfcleaguefe_report {
    matchreport {
      match {
        tickerLists {
        card =< lib.t3sports.matchNote
        card {
          filter.fields.MATCHNOTE.MINUTE.OP_GTEQ_INT = 0
          filter.fields.MATCHNOTE.TYPE.OP_IN_INT = 70,71,72
            filter.options {
              orderby.MATCHNOTE.MINUTE = DESC
              orderby.MATCHNOTE.EXTRA_TIME = DESC
              orderby.MATCHNOTE.UID = DESC
            }
          }
        }
      }
    }
  }
}
```
Und im Template:
```html
###MATCH_CARDS###
<h3>Die Karten</h3>
###MATCH_CARD###
<div class="col-sm-6">
###MATCH_CARD_ISCARD_YES###
        ###MATCH_CARD_MINUTE###: Karte für ###MATCH_CARD_PLAYER_DCNAME### 
###MATCH_CARD_ISCARD_YES###
</div>
###MATCH_CARD###
###MATCH_CARDS###
```
Wie bekomme ich jetzt hier noch die Art der Karte angezeigt? Oder sollte ich dafür eigene Subparts machen (Gelbe-, Rote-, Gelbrotekarte). Wenn das funktioniert, kann ich gerne einen PR erstellen.

Und noch eine Frage:
> Damit sollte man nun alles zusammenbasteln können. Die Subparts lassen sich auch verschachteln, so daß man z.B. einen Subpart für die Unterscheidung von Heim- und Gast-Team erstellen kann und dann innerhalb weitere Subparts für den Typ des Events einbaut.

Sorry, hier brauche ich auch noch mal hilfe. Du meinste bestimmt was wie
```
lib.t3sports.matchNote {
  subparts {
    ishome =< lib.t3sports.matchNote.subparts.isgoal
    ishome {
      # -> Marker: _ISHOME_YES###
      visible.if {
        #### wie schreibe ich hier die Bedingung?
      }
    }
  }
}
```
Ich konnte jetzt nicht rausfinden, welches Feld das Team (Heim, Gast) beinhaltet.

**Comment by digedag** [comment]
> Wie bekomme ich jetzt hier noch die Art der Karte angezeigt? Oder sollte ich dafür eigene Subparts machen (Gelbe-, Rote-, Gelbrotekarte).

Genau, hier wären eigene Subparts notwendig.
Und beim if muss ich auch immer in [der Referenz nachschauen](https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/If/Index.html). :wink:  Wenn die MatchNote zum Heim-Team gehört, dann ist das Feld `player_home` belegt:
```
lib.t3sports.matchNote {
  subparts {
    ishome =< lib.t3sports.matchNote.subparts.isgoal
    ishome {
      # -> Marker: _ISHOME_YES###
      visible.if {
          isGreaterThan.field = player_home
          value = 0
      }
    }
  }
}
```

**Comment by digedag** [comment]
Übrigens ist vielleicht auch #47 für dich interessant. Das ist zwar noch in den absoluten Startlöchern, aber ich versuche derzeit den Spielbericht auch mal per Twig zu rendern. Damit würde die gesamte Typoscript-Magie natürlich wegfallen...

**Comment by stemeda** [comment]
Danke für die Hinweise. Werde ich ausprobieren, kann aber etwas dauern, bis ich dazu komm...
