### ISSUE TITLE
Use Round from Scope richtig

### ISSUE THREAD

**Issue by mario-naether** [digedag/cfc_league_fe#45]
Hi @digedag ,
mit der config "leaguetable.useRoundFromScope" kann man im FE einstellen, ob die Tabelle zum ausgewählten Spieltag (per Dropdown ) angezeigt werden soll.
Wenn ich aber initial keinen Spieltag auswählen, wird aktuell der zuletzt komplette Spieltag angezeigt.
Muss das so?

Wenn ich keinen Spieltag auswähle, sollten doch aber alle Spiele angezeigt/berechnet werden? (RoundId=0)

Dafür hab ich die Datei angepasst:
typo3conf/ext/cfc_league_fe/util/class.tx_cfcleaguefe_util_ScopeController.php->handleCurrentRound

```
private static function handleCurrentRound($parameters, $configurations, $saisonUids, $groupUids, $compUids, $clubUids, $useObjects = false)
    {
        $roundUid = 0;
        $viewData = & $configurations->getViewData();
        // Soll eine SelectBox für Wettkämpfe gezeigt werden?
        if ($configurations->get('roundSelectionInput') && (isset($compUids) && tx_rnbase_util_Math::testInt($compUids))) {
            $currCompetition = new tx_cfcleaguefe_models_competition($compUids);
            // Die Spielrunden ermitteln

            $rounds = $currCompetition->getRounds();
            $dataArr = tx_cfcleaguefe_util_ScopeController::prepareRoundSelect($rounds, $parameters, $configurations, 'scope.rounds.', $useObjects ? '' : 'uid');
            if ($parameters->offsetGet('round') !== NULL) {
                $roundUid = $dataArr[1];
            }

            $viewData->offsetSet('round_select', $dataArr);
            $configurations->addKeepVar('round', $roundUid);
        }
        return $roundUid;
    }
```

Wenn du der gleichen Meinung bist, dann erstelle ich nochmal einen Pull-Request.

**Comment by digedag** [comment]
> mit der config "leaguetable.useRoundFromScope" kann man im FE einstellen, ob die Tabelle zum ausgewählten Spieltag (per Dropdown ) angezeigt werden soll.

Nicht ganz. Die Option entscheidet nur darüber, ob der ggf. im Scope gesetzte Spieltag in die Berechnung der Tabelle eingehen soll. Ob im FE ein DropDown gezeigt wird, gezeigt wird, entscheidet die Option **roundSelectionInput**.
Normalerweise wird die Funktion zusammen mit dem Spielplan genutzt. Man will also Tabelle und einen Spieltag zusammen anzeigen. Und da will man im Plugin keinen konkreten Spieltag setzen. Statt dessen soll automatisch auf den aktuellen Spieltag eingestellt werden. Das funktioniert noch nicht perfekt, aber die aktuelle Umsetzung kommt dem zumindest nahe.
Und nun kann man sich entscheiden, ob man die Tabelle immer passend zum ausgewählten Spieltag anzeigen will. Wenn du immer die volle Tabelle zeigen willst, dann setze die Option **leaguetable.useRoundFromScope** einfach nicht.
Ich vermute aber, daß du irgendetwas anderes vor hast... :wink:

**Comment by mario-naether** [comment]
Hi Rene, du bist ein Fuchs...
Ich weiß noch nich ganz, was du genau mit scope meinst,aber ich brauche die Option leaguetable.useRoundFromScope, da ich die Spieltags Auswahl nutzen möchte.
Wenn ich dies mache, (ohne  einen spieltag auszuwählen ) , wird bei mir der aktuell  Spieltag falsch berechnet oder/und es sollten alle Spieltage in die Berechnung einfließen.
Das passiert aktuell nicht. 

Verstehst du was ich meine? 
Evt schick ich dir mal nen paar links per Mail? 
Mfg Mario

**Comment by digedag** [comment]
Klar schickt mir einfach was. So richtig hab ich deinen Anwendungsfall noch nicht verstanden... :smile:
