### ISSUE TITLE
Handball: Diverse Warnhinweise:

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league_fe#46]
Hallo René,

ich habe wieder mal mit "Handball" getestet.

Dabei erhalte ich folgende Warnmeldungen:
Core: Error handler (FE): PHP Warning: Declaration of tx_cfcleaguefe_table_handball_Configurator::getPointsLoose($afterExtraTime, $afterPenalty) should be compatible with tx_cfcleaguefe_table_football_Configurator::getPointsLoose() in /mnt/web110/e2/66/5513066/htdocs/typo3_grau_02/typo3conf/ext/cfc_league_fe/table/handball/class.tx_cfcleaguefe_table_handball_Configurator.php line 29

Core: Error handler (FE): PHP Warning: Declaration of tx_cfcleaguefe_table_handball_Table::countGuest(&$match, $toto, tx_cfcleaguefe_table_football_Configurator $configurator) should be compatible with tx_cfcleaguefe_table_football_Table::countGuest($match, $toto, tx_cfcleaguefe_table_IConfigurator $configurator) in /mnt/web110/e2/66/5513066/htdocs/typo3_grau_02/typo3conf/ext/cfc_league_fe/table/handball/class.tx_cfcleaguefe_table_handball_Table.php line 33

Außerdem gibt es weiterhin Probleme, wenn ein Spiel unentschieden ausgegangen ist. - siehe auch https://github.com/digedag/cfc_league_fe/issues/30 ;-)

p.s. Bist eigentlich schon dazu gekommen die Tabellenberechnung für Handball anzupassen. ;-)

Ich nutze
php 7.1.10
Typo3 7.6.19
T3sports 1.1.1 (neueste Version)
T3sports FE 1.1.1 (neueste Version)
rn_base 1.5.1

**Comment by entaxi57** [comment]
Hallo René,

habe gerade die neueste Version getestet. Die 2. Warnmeldung ist leider immer noch vorhanden.

Core: Error handler (FE): PHP Warning: Declaration of tx_cfcleaguefe_table_handball_Table::countGuest(&$match, $toto, tx_cfcleaguefe_table_football_Configurator $configurator) should be compatible with tx_cfcleaguefe_table_football_Table::countGuest($match, $toto, tx_cfcleaguefe_table_IConfigurator $configurator) in /mnt/web110/e2/66/5513066/htdocs/typo3_grau_02/typo3conf/ext/cfc_league_fe/table/handball/class.tx_cfcleaguefe_table_handball_Table.php line 33

**Comment by entaxi57** [comment]
Hallo René,

sorry, habe gerade erst die neue Version getestet. Die Warnmeldungen werden nicht mehr angezeigt.

Danke.

Bernd

**Comment by digedag** [comment]
Danke für die Rückmeldung. Bei der Berechnung für Handball bin ich leider noch nicht weiter...

**Comment by entaxi57** [comment]
Hallo René,

mach dir keinen Stress damit. 

Vielleicht klappt es ja bis Ende Dezember.  Anfang Januar findet das nächste Turnier statt. Habe ja auch die Möglichkeit, die Tabelle manuell zu korrigieren. 
Am 08.11.2017, 12:20, "René Nitzsche" <notifications@github.com> schrieb:
Danke für die Rückmeldung. Bei der Berechnung für Handball bin ich leider noch nicht weiter...

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/digedag/cfc_league_fe","title":"digedag/cfc_league_fe","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/digedag/cfc_league_fe"}},"updates":{"snippets":[{"icon":"PERSON","message":"@digedag in #46: Danke für die Rückmeldung. Bei der Berechnung für Handball bin ich leider noch nicht weiter... "}],"action":{"name":"View Issue","url":"https://github.com/digedag/cfc_league_fe/issues/46#issuecomment-342788390"}}}
