### ISSUE TITLE
Logo-Marker als File-Pfad ausgeben

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league_fe#49]
Bei der Verwendung des Markers ###MATCH_HOME_LOGO### wird das Logo der Heimmannschaft mit einem Image-Tag ausgegeben.

Als Alternative wäre es praktisch, wenn man das Logo auch als URL bekäme, dann könnte man es im Template selbst entsprechend in einem Image-Tag mit individuellen Klassen usw. verarbeiten.

Wäre das möglich? Oder ist es vielleicht schon möglich?

Interessant im Grunde für alle Marker, die ein Bild ausgeben.

**Comment by digedag** [comment]
Einfach mal das Typoscript der Logos anschauen. Das findest du unter `lib.t3sports.teamLogo`. Überall wo da `IMAGE` steht, muss man nur `IMG_RESOURCE` hinschreiben. Und schon werden lediglich die URIs rausgerendert.
Das Typoscript ist an der Stelle etwas komplexer, weil das Logo an verschiedenen Stellen gesucht wird. Letztendlich ist das aber alles reines Typoscript.

**Comment by bastians** [comment]
Aah, danke für den Tipp! 👍 Werde ich direkt mal testen.
