### ISSUE TITLE
Bug with new CAL Version

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league_fe#5]
Hey,

i think since version 1.9.0 of cal (https://docs.typo3.org/typo3cms/extensions/cal/Changelog/1-9-0.html) the integration of cfc_league_fe with cal is not working due to the changed file pathes.

Could you please fix it?

Thank you!

**Comment by stemeda** [comment]
Any updates?

**Comment by bastians** [comment]
Did you fix it?

**Comment by bastians** [comment]
Any news here?

**Comment by stemeda** [comment]
The 'cal' extension seems to be unmaintained. I think this can be closed?
