### ISSUE TITLE
Team-Notiz - Typ des Werts "Media" (TNPICTURE)

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league_fe#50]
Hallo René,

standartmäßig gibt es keinen Link bei dem Marker (###TEAM_PLAYER_TNPICTURE###), der das Bild vergrößert, Zu mindestens haben ich keine Einstellungen gefunden.

- gibt es eine Möglichkeit "###TEAM_PLAYER_TNPICTURE###" in lightbox einzubinden?
- wenn ja, welche Einstellungen müssen dann hierfür im TS eingetragen werden?

.

**Comment by digedag** [comment]
Also da muss du zunächst das Typoscript etwas umbauen. Die Config für die Bilder der Team-Notes sieht so aus:
```
lib.t3sports.teamnote {
  conf.tx_cfcleague_team_notes {
    1 = IMAGE
    1.file {
      maxW = 100
      maxH = 100
      treatIdAsReference = 1
      import.cObject = USER
      import.cObject {
        userFunc=tx_rnbase_util_TSFAL->fetchFirstReference
        refField=media
        refTable=tx_cfcleague_team_notes
      }
    }
  }
}
```
Das einzelne IMAGE musst du entfernen, weil du ja nicht nur das Bild, sondern auch die URI für das größere Bild benötigst. Ich würde `tx_rnbase_util_TSFAL->printImages` nutzen:

```
lib.t3sports.teamnote {
  conf.tx_cfcleague_team_notes {
    1 = USER
    1 {
      userFunc = tx_rnbase_util_TSFAL->printImages
      refField = media
      refTable = tx_cfcleague_team_notes
      template = EXT:cfc_league_fe/res/lightboxpics.html
      subpartName = ###PICTURES###
      media {
        file = IMG_RESOURCE
        file.file.import.field = file
        file.file.maxW = 900
        file.file.maxH = 900
        thumbnail < .file
        thumbnail = IMAGE
        thumbnail.file.maxW = 100
        thumbnail.file.maxH = 100
        thumbnail.params = border="0"
        thumbnail.titleText.field = title
      }
    }
  }
}
```
Schau dir [EXT:cfc_league_fe/res/lightboxpics.html](https://github.com/digedag/cfc_league_fe/blob/e4bc7af7f51a90fedb9d6d140ee491510ff0bffb/res/lightboxpics.html) an. Das kannst du als Vorlage nutzen. Welche JS-Libs du für die Lightbox nutzt, steht dir ja frei.

**Comment by entaxi57** [comment]
Hallo René,

hat einwandfrei geklappt. Danke.
