### ISSUE TITLE
Team-Logo wird nicht immer angezeigt obwohl gesetzt

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league_fe#51]
Bei mir wird aktuell das Team-Logo nicht immer angezeigt, obwohl bei den betroffenen Mannschaften ein Verein zugewiesen ist und das dem Verein zugewiesene Logo in der Mannschaft ausgewählt. Speichere ich die Mannschaft nochmals ab, wird das Logo angezeigt.

Die Mannschaften wurden über den neuen Spielplan-Import angelegt. Anschließend habe ich über das Listen-Modul die Mannschaften im "Batch-Modus" (nennt man den so? :) ) bearbeitet und zuerst die Vereine hinzugefügt und danach die Logos. Ich habe die Vermutung, dass das damit irgendwie zusammenhängen könnt. Wäre das möglich? Ich hatte auch mal in der Datenbank geschaut, ob da eventuell keine Werte gesetzt sind aber dem ist nicht so.

Irgendwelche Ideen, woran das liegen könnte?

TYPO 7.6.31
cfc_league 1.2
cfc_league_fe 1.2

**Comment by bastians** [comment]
Ich habe mal noch ein paar zusätzliche Screenshots die zeigen, dass datentechnisch eigentlich alles korrekt sein sollte. Ich hab als Beispiel eine Mannschaft genommen, bei der aktuell kein Logo angezeigt wird, obwohl es angelegt ist.

Im Listen-Modul sieht das in der Übersicht so aus:
![typo3-listen-modul-mannschaften](https://user-images.githubusercontent.com/863722/46375967-11735d00-c695-11e8-8b5e-c5b48defba35.png)

Im Batch-Modus so:
![typo3-listen-modul-batch-modus-mannschaften-teamlogo](https://user-images.githubusercontent.com/863722/46376093-6adb8c00-c695-11e8-98ec-582d5565d269.png)

Detailansicht:
![typo3-detailansicht-mannschaft](https://user-images.githubusercontent.com/863722/46376107-75962100-c695-11e8-9bb8-a30f0886d251.png)

Und der dazu gehörige Datenbank-Eintrag:
![datenbank-eintrag](https://user-images.githubusercontent.com/863722/46376118-7fb81f80-c695-11e8-9d53-f96556b41e8f.png)

Wenn ich nun die Detailansicht nochmals speichere, dann wird das Logo angezeigt. Im Modul "Protokoll" ist dann folgendes vermerkt:
`Record 'TSF Ditzingen I' (tx_cfcleague_teams:7136) was updated. (Online). Änderungen in Feldern: t3logo,t3images.`
Wenn ich im Batch-Modus speichere, taucht nichts im Protokoll auf.

Ich habe eigentlich auch ein Dummy-Logo definiert, dass angezeigt werden sollte, wenn kein Logo vorhanden ist. Passiert aber auch nicht.

Mein TS dazu:
`lib.t3sports.dummyLogo.file = fileadmin/[...]/dummywappen.png
`

Kann ich das irgendwie weiter debuggen?

**Comment by bastians** [comment]
Ich habe mal noch zwei Datenbankeinträge verglichen. Bei dem ersten Eintrag wird das Logo nicht angezeigt, beim zweiten wird es angezeigt:
![datenbank-eintrag-vergleich](https://user-images.githubusercontent.com/863722/46376838-57312500-c697-11e8-9fdf-3e84594a57b3.png)

In den Spalten `t3logo` und `t3images` steht einmal `NULL` und beim anderen `0`. Ändere ich das `NULL` auf `0` wird das Logo angezeigt. 

Kann man das fixen oder hätten das Auswirkungen auf andere Stellen?

**Comment by bastians** [comment]
Jetzt zur neuen Saison fällt mir dieses Problem wieder auf.

Reicht es aus, wenn man die Spalten in der Tabelle `clubs` wie folgt ändert von:

Alt:
```
	t3logo text,
	t3images text,
```

Neu:

```
 	t3logo int(11) DEFAULT '0' NOT NULL,
 	t3images int(11) DEFAULT '0' NOT NULL,
```

https://github.com/digedag/cfc_league/blob/master/ext_tables.sql#L189

(Sorry, das Issue gehört wohl in das andere Projekt)

**Comment by digedag** [comment]
Der Typ in der Datenbank ist für die Funktion nicht groß relevant. Da steht eh nur die Anzahl der Zuordnungen drin, also eine Zahl. Die passt auch in ein TEXT-Feld. Aber wie kommst du auf die Spalte `t3logo`? Definiert ist nur `logo`. Und diese Spalte ist auch in der TCA konfiguriert. Und eine Spalte für sonstige Bilder kann ich im Verein gar nicht finden...
Mal zu deiner ursprünglichen Frage: 

> Bei mir wird aktuell das Team-Logo nicht immer angezeigt, obwohl bei den betroffenen Mannschaften ein Verein zugewiesen ist und das dem Verein zugewiesene Logo in der Mannschaft ausgewählt. Speichere ich die Mannschaft nochmals ab, wird das Logo angezeigt.

Das Verhalten kann ich erklären: Es muss noch der Zuordnung des Vereins immer nochmal gespeichert werden, damit das Logo direkt im Team gespeichert ist. Wenn das nicht gemacht wurde, ist im Typoscript ein Fallback drin, der auf den gewählten Verein geht und da das erste Logo anzeigt. Und genau das scheint bei dir nicht zu funktionieren. Das kann dann aber eigentlich nur ein TS-Problem sein. Sicher, daß du das Static-TS für FAL mit aktiv hast und das es nach dem normalen Static-TS der Extension geladen wird??

**Comment by bastians** [comment]
Danke für deine Rückmeldung.

> Das Verhalten kann ich erklären: Es muss noch der Zuordnung des Vereins immer nochmal gespeichert werden, damit das Logo direkt im Team gespeichert ist. 

Das ist bei mir das Problem, denke ich. Ich speichere nicht nochmals den kompletten Datensatz einer Mannschaft, da ich nicht jedes Teams nochmals öffne und bearbeite. Ich nutze die Listenansicht und klicke bei der Spalte "Teamlogo" auf Bearbeiten. Dann habe ich ja die Möglichkeit für alle Teams der Seite, das "Teamlogo" zu bearbeiten. Wenn ich dann auf "Speichern" klicke, dann sind die Logos ja dem Team eigentlich zugeordnet, werden aber nicht angezeigt.

Öffne ich einen einzelnen Teamdatensatz und speichere nochmals, dann wird das Logo angezeigt. Aber bei dem Speichervorgang wird dann eben nur der Wert "0" gesetzt bei `t3logo` und `images`, mehr scheint da nicht zu passieren.

So sieht die Einbindung meiner Statischen Templates aus:
<img width="515" alt="Bildschirmfoto 2019-08-12 um 16 24 44" src="https://user-images.githubusercontent.com/863722/62872428-c3e86780-bd1d-11e9-8127-f7e5e5a7efa4.png">

**Comment by digedag** [comment]
~~In der Liste der Static Templates fehlt **T3sports for TYPO3 6.x**. Der Name ist sicher nicht ganz günstig, weil es für alle Versionen ab 6.x notwendig ist. Wobei das Ziel besteht, das Template zukünftig zu entfernen.~~

Ach, ist ja doch drin!

**Comment by digedag** [comment]
Also, wenn du ein Team in der Listenansicht bearbeitest und dort das Vereinslogo zuordnest, dann schau mal nach, was in der Datenbank nach dem Speichern in der Spalte **logo** der Tabelle **_teams** drin steht. Da sollte die UID des FAL-Bilds des Logos drin stehen.

**Comment by bastians** [comment]
Das steht in der Datenbank bei der Mannschaft, das noch kein Logo zugeordnet hat:

<img width="1198" alt="Bildschirmfoto 2019-08-12 um 21 01 33" src="https://user-images.githubusercontent.com/863722/62890794-76cbbc00-bd44-11e9-9f47-091d9096842a.png">

Und man wenn der Mannschaft das Logo des Vereins über die Massenbearbeitung des Teamlogos zugeordnet wird, dann sieht die Datenbank wiefolgt aus:

_Listenfunktion:_
<img width="1127" alt="Bildschirmfoto 2019-08-12 um 21 07 29" src="https://user-images.githubusercontent.com/863722/62891252-87c8fd00-bd45-11e9-9a05-9d9f9b67b4b5.png">

_Datenbank:_
<img width="1191" alt="Bildschirmfoto 2019-08-12 um 21 11 05" src="https://user-images.githubusercontent.com/863722/62891340-bfd04000-bd45-11e9-9e19-76b776816534.png">

Und wenn man der Mannschaft das Logo des Vereins über die normale Detailansicht zuordnen und speichert, dann sieht die Datenbank wiefolgt aus:

<img width="1120" alt="Bildschirmfoto 2019-08-12 um 21 12 33" src="https://user-images.githubusercontent.com/863722/62891420-f60dbf80-bd45-11e9-8af0-a37a03bf0603.png">

Die ID wird m.E. korrekt gesetzt bei `logo`, es unterscheiden sich je Bearbeitungsmodus nur die Werte von `t3logo`.

**Comment by digedag** [comment]
Okay, in dem Fall kann/wird doch die Datenbank Schuld sein! Das TEXT-Feld kann `NULL` sein, beim Int-Type wird das ausgeschlossen.
Ich hab vorhin ein paar Sachen von DAM rausgenommen und dabei auch die Datentypen korrigiert. Also bitte mal pullen und dann im Install-Tool die Datenbank abgleichen. Nach der Umstellung passen die Felder dann vielleicht schon!

**Comment by bastians** [comment]
Ok, danke. Das sollte dann das Problem beheben. Teste es heute Abend aus.

Eine Rückfrage habe ich aber: Wieso ist der Default-Wert `0` und nicht `null`?

**Comment by digedag** [comment]
Das ist ein normales Referenzfeld von TYPO3. Die sind immer als NOT NULL definiert. Das spart dann im Code ggf. einen zusätzlichen Test auf `null`. Das ist aber nur eine Konvention. Man könnte das grundsätzlich auch anders machen.

**Comment by digedag** [comment]
Ich hab jetzt mal das TS für DAM entfernt. Das Static-TS File ist jetzt komplett auf FAL umgestellt. Die zusätzliche Datei wurde entfernt.
Und das Ticket mach ich bei der Gelegenheit auch zu. Sollte sich ja erledigt haben.
