### ISSUE TITLE
The each() function is deprecated

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league_fe#56]
Hallo René,

ich habe gerade meine Vereinswebsite auf PHP 7.3 upgedatet und bekommt jetzt folgende Meldung.

Core: Error handler (FE): PHP Runtime Deprecation Notice: The each() function is deprecated. This message will be suppressed on further calls in .../typo3conf/ext/cfc_league_fe/Classes/Utility/Signs.php line 50 Änderungen in Feldern: table_marks.

**Comment by entaxi57** [comment]
Hallo René,

Fehler wird nicht mehr angezeigt nachdem ich die neue Version eingespielt habe.

Danke für die schnelle Behebung.

**Comment by digedag** [comment]
Danke dir für den Hinweis! Ich bin aktuell noch hauptsächlich mit 7.2 unterwegs.

**Comment by entaxi57** [comment]
Hallo René,

ich habe noch eine Meldung für dich:
Core: Error handler (FE): PHP Runtime Deprecation Notice: The each() function is deprecated. This message will be suppressed on further calls in .../typo3conf/ext/cfc_league_fe/views/class.tx_cfcleaguefe_views_LeagueTableAllTime.php line 208 Änderungen in Feldern: date.

**Comment by entaxi57** [comment]
Hallo René,

Auch diese Meldung tritt nicht mehr auf. Danke
