### ISSUE TITLE
LeaguetableAllTime

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league_fe#57]
Hallo René,

bei LeaguetableAllTime kann man ja die unterschiedlichen Punktesysteme anzeigen lassen. Ich finde leider keine Möglichkeit, standardmäßig auf das 2-Punktesystem umzustellen. Es wird zuerst immer das 3-Punktesystem angezeigt, dass wir beim Handball nicht kennen. Nur wenn ich "Selectbox für Punktsystem anzeigen" markiere kann ich von 3- auf 2-Punktesystem umstellen.

Habe ich da eine Einstellung übersehen?

**Comment by digedag** [comment]
Also primär sollte das Punktsystem genutzt werden, das im jeweiligen Wettbewerb gesetzt ist. Für die Allzeit-Tabelle wird aber noch die alte Berechnung genutzt. Die "kennt" diese Einstellung nicht. Das muss ich mal mit umstellen. Danke für den Hinweis!

**Comment by digedag** [comment]
Mit Umstellung auf der Berechnung wird nun der Default-Punkte-Modus aus den verwendeten Wettbewerben geholt. Das Problem sollte damit behoben sein. Und laut Hinweis in #77 scheint dem ja auch so zu sein.
