### ISSUE TITLE
Support Typo3 CMS 7 LTS

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league_fe#6]
This fall the Typo3 CMS 7 LTS will be released and it would be nice to run T3Sports with it.

**Comment by bastians** [comment]
Any plans for this so far?

**Comment by digedag** [comment]
Ich habe jetzt erstmal "blind" alle Klassen umgestellt. Spielplan und Spielbericht wurden mir angezeigt. Zu mehr Tests fehlt mir die Zeit. Wenn hier jemand testen würde, wäre das sehr gut... :wink: 
Für Tests unbedingt mit den aktuellen Git-Versionen von rn_base und cfc_league arbeiten.

**Comment by stemeda** [comment]
Ich habe von Typo3 6.2 auf Typo3 7.6 geupdated. Die Ausgabe von allen Inhalten des Plugins werden

- nur angezeigt, wenn ich eine aktive Backend-Session habe
- im Backend den Seiteninhalt speicher, im Install-Tool alle Caches lösche und dann das Frontend aktuallisiere. Wenn ich dann im Backend etwas anderes mache (z.B. eine Extension installieren) ist die Anzeige im Frontend wieder weg und ich muss die Schritte wiederholen. Die Schritte sind dabei für jeden Seiteninhalt einzeln durchzuführen. Ich kann nicht alle Seiteninhalte öffnen, speichern und dann zum Schluss den Cache löschen, sondern muss das für jeden Seiteninhalt einzeln machen.

Ich habe die aktuellen Versionen von `rn_base`, `cfc_league` und `cfc_league_fe`. Andere Plugins `news` oder `cal` zeigen den Inhalten im FE ohne Probleme an.

**Comment by digedag** [comment]
Ich kann das Verhalten leider nicht reproduzieren. Ich kann aber leider auch deiner Schrittfolge nicht ganz folgen. :wink: 

Sind die beiden Punkte verodert? Also kannst du grundsätzlich nur dann was im FE sehen, wenn du im BE eingeloggt bist? Oder führen die Aktionen in Schritt 2 dazu, daß du den Inhalt dann auch ohne Anmeldung im BE siehst?

Was meinst du mit den Seiteninhalten? Die Plugins oder irgendwelche andere Inhalte, wie Text/Bild?
Werden von den Plugins die Überschriften noch angezeigt? Hast du die 7.6 im Composer-Modus laufen? Also Installation von Extensions nur per Composer?

Und gibt es ggf. im PHP-Errorlog irgendwelche Meldungen? Eventuell auch mal [mklog](https://github.com/DMKEBUSINESSGMBH/typo3-mklog) installieren. Da werden ggf. auch noch paar sachdienliche Hinweise reingeschrieben...

**Comment by stemeda** [comment]
Danke für das schnelle Feedback.

Also die beiden Möglichkeiten sind parallel. Wenn ich eine aktive Backend-Session habe sehe ich immer den FE-Inhalt des Plugins (Tabellen, Ergebnisse, Team, ...). Alternativ sehe ich den Inhalt des Plugins, wenn ich die Schritte

1. FE-Seiteninhalt-Datensatz im Backend speichern
1. Caches im Install-Tool leeren
1. FE-Seite aufrufen

durchführe. Bei diesen Schritten kann es aber sein, dass die Inhalte wieder verschwinden z.B. wenn ich den FE-Cache leere.

Die Überschrift vom Plugin werden immer angezeigt.

Im Typo3-Protokoll habe ich den Fehler:
```
Core: Error handler (FE): PHP Runtime Deprecation Notice: Non-static method tx_cfcleaguefe_models_competition::findAll() should not be called statically, assuming $this from incompatible context in .../typo3conf/ext/cfc_league_fe/actions/class.tx_cfcleaguefe_actions_LeagueTable.php line 63
```
Im Dev-Log:
```
Key: extbase
Message: The singleton "TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager" needs a prototype in "injectQueryGenerator". This is often a bad code smell; often you rather want to inject a singleton.
Called From: Container.php, line 271
```

Alle anderen Plugins zeigen FE-Inhalte an, es betrifft also nur `cfc_league_fe`. Typo3 ist im Debug-Modus, es werden aber keine Fehler im FE angezeigt

**Comment by stemeda** [comment]
Ich hab jetzt grade den Fehler

`Fatal error: Class 'PHPUnit_Framework_TestCase' not found in .../typo3conf/ext/rn_base/tests/class.tx_rnbase_tests_BaseTestCase.php on line 36 ` 

im FE angezeigt bekommen. Beim Neuladen der FE-Seite (ohne sonstige Änderungen) war der Fehler weg. Auf der FE-Seite wird eine Tabelle ausgegeben. Die Seite wurde ohne aktive Backend-Session aufgerufen.

**Comment by digedag** [comment]
Ich hab die Warnung mal rausgebaut, daß wird aber das Problem nicht lösen. Wenn nur die Überschrift angezeigt wird, dann gibt es meiner Ansicht nach zwei mögliche Fehlerquellen: Entweder wird das Typoscript der Extension nicht richtig eingebunden, bzw. fliegt aus irgendeinem Grund wieder raus.
Ansonsten kann es auch noch am Class-Loader liegen. In 7.6 wird der Composer für das Class-Loading verwendet. Für T3sports habe ich da aber noch nichts vorbereitet. Ich kann mich aber da mal kundig machen. Wird aber erst in der kommenden Woche werden (Klingt besser als nächstes Jahr, oder? :rofl: ).

**Comment by stemeda** [comment]
Im Adminpanel habe ich unter `Typoscript->Nachrichten anzeigen` für den TypoScript Key `page` ca. 90 mal den Eintrag `Content Object "" does not exist`. Kann ich irgendwie prüfen, ob z.B. das Typoscript der Extension nicht richtig ist bzw. wieder entfernt wird?

Ich hab die Erweiterung mal geupdated und bekomme jetzt den Fehler `Fatal error: Cannot make non static method tx_cfcleague_models_Competition::findAll() static in class tx_cfcleaguefe_models_competition in .../typo3conf/ext/cfc_league_fe/models/class.tx_cfcleaguefe_models_competition.php on line 35 `. Deswegen bin ich wieder eine Version zurück https://github.com/digedag/cfc_league_fe/tree/2ac8458b55ff9ba11fb9a7ee13c6296b4cad56c2

**Comment by stemeda** [comment]
Auf einer FE-Seite, in der ich einen Spielplan ausgebe, bekomme ich diese Fehlermeldung für jedes Team im Spielplan angezeigt:
```
array(4 items)
   caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
   ERROR => 'You have an error in your SQL syntax; check the manual that corresponds to y
      our MySQL server version for the right syntax to use near 'FROM tx_cfcleague
      _teams WHERE uid='****' AND NOT deleted LIMIT 1' at line 1' (211 chars)
   lastBuiltQuery => 'SELECT FROM tx_cfcleague_teams WHERE uid='****' AND NOT deleted LIMIT 1' (73 chars)
   debug_backtrace => 'call_user_func#34 // {closure}# // TYPO3\CMS\Frontend\Http\Application->r
      un#33 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#78 // TYPO3\CMS\Fro
      ntend\Http\RequestHandler->handleRequest#302 // TYPO3\CMS\Frontend\Page\P
      ageGenerator::renderContent#216 // TYPO3\CMS\Frontend\ContentObject\ContentO
      bjectRenderer->cObjGet#210 // TYPO3\CMS\Frontend\ContentObject\ContentObj
      ectRenderer->cObjGetSingle#805 // TYPO3\CMS\Frontend\ContentObject\Conten
      tObjectRenderer->render#859 // TYPO3\CMS\Frontend\ContentObject\FluidTemp
      lateContentObject->render#943 // TYPO3\CMS\Frontend\ContentObject\FluidTe
      mplateContentObject->renderFluidView#102 // TYPO3\CMS\Fluid\View\Abstract
      TemplateView->render#300 // FluidCache_Standalone_layout_Default_07c91cf3
      b65d4b767f87d52fcd3f165043c0f0ba->render#189 // TYPO3\CMS\Fluid\ViewHelpe
      rs\RenderViewHelper::renderStatic#175 // TYPO3\CMS\Fluid\View\AbstractTempla
      teView->renderSection#121 // FluidCache_Standalone_template_file_DefaultS
      ubNavLeft_d9838e0d5fb52d986c166215d6090b68cf98b1fb->section_62bce9422ff2d
      14f69ab80a154510232fc8a9afd#230 // TYPO3\CMS\Fluid\Core\ViewHelper\AbstractV
      iewHelper->initializeArgumentsAndRender#101 // TYPO3\CMS\Fluid\Core\ViewH
      elper\AbstractViewHelper->callRenderMethod#249 // call_user_func_array#26
      8 // TYPO3\CMS\Fluid\ViewHelpers\CObjectViewHelper->render# // TYPO3\CMS\
      Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#119 // TYPO3\
      CMS\Frontend\ContentObject\ContentObjectRenderer->render#859 // TYPO3\CMS
      \Frontend\ContentObject\ContentObjectArrayContentObject->render#943 // TY
      PO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGet#41 // TYPO3
      \CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#805 // T
      YPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render#859 // TYPO
      3\CMS\Frontend\ContentObject\ContentContentObject->render#943 // TYPO3\CM
      S\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#97 // TYPO3
      \CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle#841 // T
      YPO3\CMS\Frontend\Co...' (5123 chars)
```

Ich hoffe, die Infos helfen etwas weiter 😃

**Comment by digedag** [comment]
Bitte mal ein neues Ticket für diesen Fehler anlegen. Es scheint sich auch um unterschiedliche Probleme zu handeln.

**Comment by stemeda** [comment]
Es funktioniert soweit nach einem Update auf Typo3 7.6.15. Danke für die Unterstützung!
