### ISSUE TITLE
LeagueTableAllTime - getSubpart() Error

### ISSUE THREAD

**Issue by al-daten** [digedag/cfc_league_fe#62]
Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::getSubpart() | Error thrown in file .../typo3conf/ext/cfc_league_fe/views/class.tx_cfcleaguefe_views_LeagueTableAllTime.php in line 64.

**Comment by digedag** [comment]
Thank's for report. Should be fixed in master. Could you test it again?

**Comment by al-daten** [comment]
Yes, it's fixed. Thank you.
