### ISSUE TITLE
Mehrere Wettbewerbe + Altersgruppen im FE nicht möglich

### ISSUE THREAD

**Issue by mario-naether** [digedag/cfc_league_fe#7]
Hi,

über den Subpart "###COMPETITION_SELECTION###" lasse ich mir z.b. 2 Wettbewerbe anzeigen, welche wiederum 2 Altersgruppen zugeordnet sind.
Im Frontend erscheint aber nur ein Wettbewerb.
Erst nachdem ich in der Datei "cfc_league_fe/search/class.tx_cfcleaguefe_search_Builder.php" die Zeile 
`$fields['COMPETITION.AGEGROUP'][OP_EQ_INT] = $groupUids;`
in
`$fields['COMPETITION.AGEGROUP'][OP_IN_INT] = $groupUids;`
geändert habe, kommen auch 2 Wettbewerbe im Frontend raus.

Leider lässt sich das nicht per xclass erweitern, da es ein static call ist.
Kann das noch angepasst werden?

**Comment by digedag** [comment]
Was willst du anpassen? Den Static Call entfernen oder den Such-Operator? :wink: 
Den Operator kann ich natürlich austauschen. Da spricht nichts dagegen.

**Comment by mario-naether** [comment]
Hi, 

mir würde es völlig reichen, wenn du den Operator auf "OP_IN_INT" anpasst. 
Vielen Dank 
Mario
