### ISSUE TITLE
cmpWeight - models/class.tx_cfcleaguefe_models_profile.php line 118

### ISSUE THREAD

**Issue by derhecht** [digedag/cfc_league_fe#73]
Warning: usort() expects parameter 2 to be a valid callback, function 'cmpWeight' not found or invalid function name

mentioned/called function is (no longer) available - please re-add or remove call.

**Comment by digedag** [comment]
Das wurde schon vor einiger Zeit gefixed. Allerdings gab es seither noch kein TER-Release. Aktuell laufen relativ viele Codeumstellungen und die will ich gern erst vollständig beenden, bevor ich wieder was in TER schiebe.
