### ISSUE TITLE
function implode() - Order of parameters

### ISSUE THREAD

**Issue by iresults-tma** [digedag/cfc_league_fe#76]
Since PHP 7.4 passing the separator after the array (i.e. using the legacy signature) has been deprecated. At various places in the code comes accordingly the warning

`PHP Runtime Deprecation Notice: implode(): Passing glue string after array is deprecated. Swap the parameters in xxx`

**Comment by digedag** [comment]
Thanks for hint. I was not aware about the wrong parameter order. But there were many occurrences indeed!
