### ISSUE TITLE
Kein Aufruf nach Update mehr möglich

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league_fe#77]
Hallo René,

ich hatte gerade versucht, die neueste Version von cfc_league, cfc_league_fe und rn_base zu installieren.

Beim Aufruf der einzelnen Seiten erhalten ich folgende Fehlermeldungen:

Frontend:
Call to undefined method System25\T3sports\Service\TeamService::getAgeGroup()

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method System25\T3sports\Service\TeamService::getAgeGroup() | Error thrown in file /.../typo3conf/ext/cfc_league_fe/Classes/Frontend/Marker/TeamMarker.php in line 141. Requested URL: ... 

Backend --> T3Sports:
Call to undefined method System25\T3sports\Service\CompetitionService::getNumberOfMatches()

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method System25\T3sports\Service\CompetitionService::getNumberOfMatches() | Error thrown in file /.../typo3conf/ext/cfc_league/Classes/Model/Competition.php in line 366. Requested URL: http://.../typo3/index.php?M=web_CfcLeagueM1&moduleToken=--AnonymizedToken--&id=1034 

Ich nutze:
cfc_league 1.8.0 (von github am 31.05.2022 übernommen)
cfc_league_fe 1.7.2 (von github am 31.05.2022 übernommen)
rn_base 1.15.3
TYPO3: 8.7.27
php: 7.4.29
MySQL: 5.7.38

**Comment by digedag** [comment]
Hallo Bernd,

das Update war keine gute Idee. Du solltest erstmal noch auf die vorherigen Versionen wechseln. Ich bin gerade dabei einen stabilen Stand aufzubauen. Bei der Backend-Extension hab ich inzwischen eine gewisse Stabilität drin. Das wird wohl die 1.8 werden. Allerdings muss ich auch die Frontend-Extension noch testen und final anpassen.

Die beiden Fehler, die du bekommst, sollten aber eigentlich nicht auftauchen. Wie hast du das Update gemacht? Über Composer oder einfach in den Extensions ein "git pull"? Letzteres ist ungünstig, weil da der Classloader nicht aktualisiert wird. Über Composer musst du aber auch Anpassungen machen, weil die Entwicklungsstände sonst nicht geladen werden.

Wenn du den Entwicklungsstand holen willst, dann du in der composer.json bei den Extensions rn_base, cfc_league und cfc_league_fe jeweils die folgenden Angaben machen:

```json
        "digedag/rn-base": "dev-master",
        "digedag/cfc-league": "dev-master",
        "digedag/cfc-league-fe": "dev-master",
```
Danach sollte dir der Composer bei einem `composer update` die letzten Stände holen und auch den Classloader korrekt initialisieren.

Die finale Version 1.8 ist nicht mehr weit weg, aber ich muss halt noch paar Tests machen. Und es hängen ja auch noch andere Extension mit dran. Tut mir leid, wegen der Probleme.

**Comment by entaxi57** [comment]
Hallo René,

ich installiere die Updates immer erst in meiner Testumgebung. Deshalb ist es nicht ganz so schlimm, dass das Update nicht geklappt hat.

Ich habe bisher die "rn_base" über TER installiert. "cfc-league" und "cfc-league-fe" installiere ich wie folgt:

- Extensions deaktiviert
- Inhalt der Ordner von "cfc_league" und "cfc_league_fe" per ftp-Zugriff gelöscht
- Zip-Datei entpackt und den Inhalt in die jeweiligen Ordner kopiert.
- Extensions aktiviert

Bisher hat es immer einwandfrei geklappt.

p.s. Ich muss dazu noch sagen, dass ich ein absoluter "Windows"-Mensch bin 😉

Bernd

**Comment by digedag** [comment]
Kannst du das Update bitte nochmal wiederholen? Die Fehler sind nun hoffentlich behoben. :slightly_smiling_face:

**Comment by entaxi57** [comment]
Hallo René,bin zur Zeit im Urlaub. Werde es gerne nach dem 10. Juli versuchen. Bernd Am 27.06.22, 21:29 schrieb "René Nitzsche" ***@***.***>:

   
  Kannst du das Update bitte nochmal wiederholen? Die Fehler sind nun hoffentlich behoben. 🙂

**Comment by digedag** [comment]
Dann wünsch ich einen schönen Urlaub! :smiley:

**Comment by entaxi57** [comment]
Hallo René,

ich habe gerade folgende Versionen installiert:
rn_base 	1.15.3 - über TER installiert
cfc_league 	1.8.2 - über TER installiert
cfc_league_fe 	1.8.2 - über TER installiert
t3sponsors 	1.2.0 - bereits vorhanden

Jetzt sieht es wieder sehr gut aus. Bisher funktioniert alles wieder.

Danke

Bernd

**Comment by entaxi57** [comment]
Hallo René,

leider ist mir doch noch etwas aufgefallen.

Bei der "LeaguetableAllTime" werden die Vereinslogos nicht korrekt angezeigt bzw. einem falschen Verein zugewiesen.

Außerdem wird beim aktivieren von "Selectbox für Punktsystem anzeigen" folgendes angezeigt:
"0 ###CONTROL_POINTSYSTEM_POINT2_LINK### ###CONTROL_POINTSYSTEM_POINT2### ###CONTROL_POINTSYSTEM_POINT2_LINK###"

Dafür scheint das Problem #57 behoben zu sein.

Bernd

**Comment by digedag** [comment]
Hallo Bernd,

das TS für die Logos hab ich gefixt. Bei den Controls stimmten die Labels nicht mehr. Das allerdings nur Marker angezeigt werden, diesen Effekt konnte ich nicht erzeugen. Schau mal, ob die Änderungen helfen! :slightly_smiling_face:

**Comment by entaxi57** [comment]
Hallo René,

die Logos sind jetzt wieder richtig zugeordnet. 
Die Marker werden immer noch angezeigt. Da ich aber diese nicht mehr benötige, da jetzt standartmäßig das 2-Punkte-System und nicht mehr automatisch das 3-Punkte-System angezeigt wird, habe ich nicht mehr geschaut, woran es bei mir liegt.

Danke für deine gute Arbeit

Berrnd
