### ISSUE TITLE
Teamdarstellung

### ISSUE THREAD

**Issue by al-daten** [digedag/cfc_league_fe#78]
UNCAUGHT EXCEPTION FOR VIEW: tx_cfcleaguefe_actions_TeamView

MESSAGE: PHP Warning: Declaration of System25\T3sports\Frontend\Marker\ProfileMarker::prepareLinks(System25\T3sports\Model\Profile $profile, $marker, &$markerArray, &$subpartArray, &$wrappedSubpartArray, $confId, $formatter, $template) should be compatible with Sys25\RnBase\Frontend\Marker\SimpleMarker::prepareLinks($item, $marker, &$markerArray, &$subpartArray, &$wrappedSubpartArray, $confId, $formatter, $template) in /typo3conf/ext/cfc_league_fe/Classes/Frontend/Marker/ProfileMarker.php line 129

STACK: TYPO3\CMS\Core\Error\Exception: PHP Warning: Declaration of System25\T3sports\Frontend\Marker\ProfileMarker::prepareLinks(System25\T3sports\Model\Profile $profile, $marker, &$markerArray, &$subpartArray, &$wrappedSubpartArray, $confId, $formatter, $template) should be compatible with Sys25\RnBase\Frontend\Marker\SimpleMarker::prepareLinks($item, $marker, &$markerArray, &$subpartArray, &$wrappedSubpartArray, $confId, $formatter, $template) in /typo3conf/ext/cfc_league_fe/Classes/Frontend/Marker/ProfileMarker.php line 129 in /typo3_src/typo3_src-10.4.34/typo3/sysext/core/Classes/Error/ErrorHandler.php:134

**Comment by al-daten** [comment]
changed line 129 in cfc_league_fe/Classes/Frontend/Marker/ProfileMarker.php
from
protected function prepareLinks(Profile $profile, $marker, &$markerArray, &$subpartArray, &$wrappedSubpartArray, $confId, $formatter, $template)
to
protected function prepareLinks($profile, $marker, &$markerArray, &$subpartArray, &$wrappedSubpartArray, $confId, $formatter, $template)

This seems to work for me.

**Comment by digedag** [comment]
Closed as already fixed. Thanks for report anyway. :+1:
