### ISSUE TITLE
UNCAUGHT EXCEPTION FOR VIEW: tx_cfcleaguefe_actions_TeamView

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league_fe#9]
Im Zuge meiner Migration von TYPO3 4.7 zu 6.2 taucht plötzlich bei der Ausgabe der Teamview wieder folgende Fehlermeldung auf:

```
UNCAUGHT EXCEPTION FOR VIEW: tx_cfcleaguefe_actions_TeamView

Message:
SQL QUERY IS NOT VALID
The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay
SELECT distinct tx_cfcleague_teams.uid, tx_cfcleague_teams.comment, tx_cfcleague_teams.name, tx_cfcleague_teams.short_name, tx_cfcleague_teams.coaches, tx_cfcleague_teams.players, tx_cfcleague_teams.supporters, tx_cfcleague_teams.coaches_comment, tx_cfcleague_teams.players_comment, tx_cfcleague_teams.supporters_comment, tx_cfcleague_teams.dam_images FROM tx_cfcleague_teams INNER JOIN tx_cfcleague_competition c ON FIND_IN_SET(tx_cfcleague_teams.uid, c.teams) AND c.hidden=0 AND c.deleted=0 WHERE tx_cfcleague_teams.club = 2 AND c.saison IN (14) AND c.agegroup IN (27) AND tx_cfcleague_teams.deleted=0 AND tx_cfcleague_teams.hidden=0

...
```

Beispiel mit Debug-Infos: http://mig.fvloechgau.de/index.php?id=55

Ich hatte das Problem schon mal, damals hatte ich so gelöst: http://www.typo3.net/forum/thematik/zeige/thema/115831/

D.h. ich habe in der Datei class.tx_cfcleaguefe_models_club.php ein mysql_query('SET SQL_BIG_SELECTS=1'); in Zeile 70 eingefügt. Wenn ich das wieder mache, kommt der Hinweis, dass das depreciated sei.

**Comment by digedag** [comment]
Was ist da deprecated? Vermutlich der PHP-Befehl **mysql_query**. Die Anweisung `SET SQL_BIG_SELECTS=1` kannst du doch im INSTALL-Tool bei den MySQL-Optionen setzen. Damit wird das bei jeder Anfrage gesetzt...

**Comment by bastians** [comment]
Ja, genau. Wo kann man das im INSTALL-Tool setzen? Ich finde da leider nichts und auch wenn ich im Netz suche gibt es da quasi keine Infos. 

Generell scheint das Problem auch durch auch eine doofe Restriktion von Hosteurope hervorgerufen zu werden.

**Comment by digedag** [comment]
Das ist das Feld unter **$TYPO3_CONF_VARS[SYS][setDBinit]**.

**Comment by bastians** [comment]
Ah, danke! Scheint zu greifen. Nun kommt aber eine andere Fehlermeldung...

```
UNCAUGHT EXCEPTION FOR VIEW: tx_cfcleaguefe_actions_TeamView
CODE: 1
MESSAGE: PHP Runtime Deprecation Notice: Non-static method Signs::getInstance() should not be called statically, assuming $this from incompatible context in [...]/typo3conf/ext/cfc_league_fe/models/class.tx_cfcleaguefe_models_profile.php line 289
```

Siehe auch http://mig.fvloechgau.de/index.php?id=204&cfc_league_fe%5Bsaison%5D=13

**Comment by bastians** [comment]
Ok, hat sich erledigt. Ich habe von PHP 5.6 auf PHP 5.5 umgestellt. Nun läuft es. Ist die Extension noch nicht PHP 5.6 ready?

**Comment by digedag** [comment]
Das Ticket sollte sich erledigt haben...
